### ISSUE TITLE
describe_project_versions function not working

### ISSUE THREAD

**Issue by saketh72** [bobbruno/aws-rekognition-cl-demo#1]
what should we keep in the place of 

def get_project(project_name="construction-object-recognition-v3"):
    try:
        project = reko.create_project(ProjectName=project_name)['ProjectArn']
    except reko.exceptions.ResourceInUseException:
        project = 'arn:aws:rekognition:us-east-1:113147044314:project/construction-object-recognition-v3/1582839055056'
    return(project)

it is showing  cross account access denied

**Comment by bobbruno** [comment]
This repo was for a demo from when I worked at AWS, for a specific case - that's why the exception has a hardcoded project. That project and the associated account don't even exist anymore, and TBH I should never have hardcoded the AWS account ID in there.

The general solution would be to use the `describe_projects` to find the project ARN. `ResourceInUseException` essentially means that a project with that name already exists.

A possible solution could look like this:

```{python}
def get_project(project_name="construction-object-recognition-v3"):
    try:
        project = reko.create_project(ProjectName=project_name)['ProjectArn']
    except reko.exception.ResourceInUseException:
        project = [
            p['ProjectArn'] 
                for p in reko.describe_projects(ProjectNames=[project_name])['ProjectDescriptions']
        ][0]
    return project
```

Note that if there are more than 100 Rekognition projects, you'd have to implement pagination on the call to `describe_projects`. You can find more information on the [boto3 client for Rekognition docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rekognition.html#client)

**Comment by saketh72** [comment]
but thanks though it worked! 🙂

**Comment by saketh72** [comment]
do you have any idea on how much time will it take to train a model in
Amazon rekognition?
I have put 500 images as an input... it is taking more than 5 hours to
train... please help me

**Comment by bobbruno** [comment]
I'm sorry, but I don't know exactly how long - big datasets can take a while. I suggest you start with a smaller set of images (I've seen decent results with just 20, maybe a 100 could be enough). But I don't work with AWS anymore, and even then, I never did much with Rekognition.

**Comment by saketh72** [comment]
the data set that you kept in the github repo... 100 images from that
dataet is enough?

**Comment by saketh72** [comment]
so, I ran the code in google colab with GPU.... while training the model in
Amazon rekognition... will it use the GPU or my laptop's CPU?

**Comment by saketh72** [comment]
so, I ran the code in google colab with GPU... while training in amazon
rekognition will it use my laptop CPU or google colab GPU?... can you
please help me

**Comment by saketh72** [comment]
how can I get good f score... I have trained the entire dataset but still
it is just 0.368.. please help me
